//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources_ZH-CN.rc
//
#define ID_SEPARATOR                    0
#define VS_VERSION_INFO                 1
#define IDD_MOUNT                       9
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define AFX_IDC_LISTBOX                 100
#define IDS_ABOUTBOX                    101
#define AFX_IDC_CHANGE                  101
#define AFX_IDC_BROWSER                 102
#define IDD_CRYPTPROPERTYPAGE           103
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_DEF               128
#define IDD_CREATE                      131
#define IDR_MENU1                       133
#define IDR_PopUps                      133
#define IDI_ICON1                       136
#define IDI_ICON2                       137
#define IDI_ICON3                       144
#define IDI_DRIVE                       144
#define IDD_SETTINGS                    145
#define IDD_MOUNTMANAGER                147
#define IDD_FSINFO                      149
#define IDD_MORESETTINGS                151
#define AFX_IDC_PRINT_DOCNAME           201
#define AFX_IDC_PRINT_PRINTERNAME       202
#define AFX_IDC_PRINT_PORTNAME          203
#define AFX_IDC_PRINT_PAGENUM           204
#define IDS_PLAIN_TEXT                  208
#define IDS_PASSWORD_EMPTY              209
#define IDS_PASSWORD_REPEAT_EMPTY       210
#define IDS_PASSWORD_DO_NOT_MATCH       211
#define IDS_PATH_EMPTY                  212
#define IDS_PATH_DOES_NOT_EXIST         213
#define IDS_PATH_COULD_NOT_CREATE       214
#define IDS_CREATED_FORWARD_FS          215
#define IDS_CREATED_REVERSE_FS          216
#define IDS_DIRECTORY_NOT_EMPTY         217
#define IDS_COULD_NOT_LOCK_BUFFER       218
#define IDS_UNABLE_LOCK_BUFFERS         219
#define IDS_MB_REQUIRED                 224
#define IDS_GB_REQUIRED                 225
#define IDS_FSINFO_YES                  240
#define IDS_FSINFO_NO                   241
#define IDS_FSINFO_NA                   242
#define IDS_FSINFO_REVERSE              243
#define IDS_FSINFO_FORWARD              244
#define IDS_FSINFO_KB                   245
#define IDS_FSINFO_SEC                  246
#define IDS_FSINFO_INFINITE             247
#define IDS_FSINFO_NAME_ENCRYPTION_NO   248
#define IDS_PASS_CANNOT_BE_EMPTY        256
#define IDS_UNABLE_LOCK_BUFFER          257
#define IDS_UNABLE_GET_PASS             258
#define IDS_UNABLE_GET_LIST             259
#define IDS_UNABLE_GET_SELECTED         260
#define IDS_UNABLE_FIND_ITEM            261
#define IDS_UNABLE_GET_LETTER           262
#define IDS_MPOINT_ALREADY_USED         263
#define IDS_UNABLE_GET_WINDOW           264
#define IDS_PATH_ZERO                   265
#define IDS_UNABLE_GET_CONF_WINDOW      266
#define IDS_ALREADY_MOUNTED             267
#define IDS_UNABLE_GET_SESSION_ID       268
#define IDS_UNABLE_GET_PROCESS_SESSION_ID 269
#define IDS_SESSION_ID_ZERO             270
#define IDS_UNABLE_SAVE_PASS            271
#define IDS_TOOLTIP_ENABLE_SAVE_PASS    272
#define IDS_DRIVE_WITHOUT_MOUNTED_FS    273
#define IDS_CANNOT_UNMOUNT              274
#define IDS_SOME_DRV_NOT_DISMOUNTED     275
#define IDS_UNABLE_DISMOUNT             276
#define IDS_UNABLE_UPDATE_LABELS        277
#define IDS_FAIL_RETRIVE_MPOINT         278
#define IDS_FAIL_RETRIVE_PASS           279
#define IDS_PATH_NOT_SUITABLE_MPOINT    280
#define IDS_MPOINT_ALREADY_ADDED        281
#define IDS_DISMOUNT_ALL_ON_EXIT        282
#define IDS_COLUMN_HEADER_MOUNT_POINT   288
#define IDS_COLUMN_HEADER_PATH          289
#define IDS_CANCELED_BY_USER            290
#define IDS_MENU_ADD_MOUNT_POINT        304
#define IDS_MENU_OPEN                   305
#define IDS_MENU_PROPERTIES             306
#define IDS_MENU_DISMOUNT               307
#define IDS_MENU_DELETE_MPOINT          308
#define IDS_LVIEW_COPYRIGHT_CPPCRYPTFS  320
#define IDS_LVIEW_COPYRIGHT_OPENSSL     321
#define IDS_LVIEW_COPYRIGHT_RAPIDJSON   322
#define IDS_LVIEW_COPYRIGHT_DOKANY_MIR  323
#define IDS_LVIEW_COPYRIGHT_DOKANY_LIB  324
#define IDS_LVIEW_COPYRIGHT_SECURE_EDIT 325
#define IDS_LVIEW_COPYRIGHT_GETOPT_PORT 326
#define IDS_LVIEW_COPYRIGHT_AES_SIV     327
#define IDS_SELECT_DIRECTORY            352
#define IDS_COPYRIGHT                   368
#define IDS_ABOUT_COPYRIGHT             369
#define IDS_LIBRARY_VERSIONS            370
#define IDS_AESNI_DETECTED              371
#define IDS_AESNI_NOT_DETECTED          372
#define IDS_ADMIN                       373
#define IDS_ERR_GET_OPENSSL_VERSION     374
#define IDS_TTL_INFINITE                400
#define IDS_TTL_SEC_1                   401
#define IDS_TTL_SEC_2                   402
#define IDS_TTL_SEC_5                   403
#define IDS_TTL_SEC_10                  404
#define IDS_TTL_SEC_15                  405
#define IDS_TTL_SEC_30                  406
#define IDS_TTL_SEC_45                  407
#define IDS_TTL_SEC_60                  408
#define IDS_TTL_SEC_90                  409
#define IDS_TTL_MIN_2                   410
#define IDS_TTL_MIN_5                   411
#define IDS_TTL_MIN_10                  412
#define IDS_TTL_MIN_15                  413
#define IDS_TTL_MIN_30                  414
#define IDS_TTL_HOUR_1                  415
#define IDS_PASS_WILL_NOT_BE_SAVED      432
#define IDS_UNABLE_COUNT_SAVED_PASS     433
#define IDS_DELETE_ALL_SAVED_PASS       434
#define IDS_UNABLE_DELETE_SAVED_PASS    435
#define IDS_NEVER_SAVE_HISTORY_HINT     436
#define IDS_UNABLE_DELETE_HISTORY       437
#define IDS_UNABLE_OPEN_HISTORY         448
#define IDS_ERR_DELETING_HISTORY        449
#define IDS_ERR_DELETING_REG_VALUE      450
#define IDS_IS_STILL_IN_USE             451
#define IDS_FS_IS_STILL_IN_USE          452
#define IDS_INVALID_MPOINT              480
#define IDS_MPOINT_DIR_NOT_EXIST        481
#define IDS_MPOINT_DIR_EMPTY_NTFS       482
#define IDS_LETTER_MPOINT_ALREADY_USE   483
#define IDS_FAILED_ALLOCATE_TDATA       484
#define IDS_UNABLE_LOAD_CONF            485
#define IDS_PASS_INCORRECT              486
#define IDS_UNABLE_INIT_EME             487
#define IDS_UNABLE_INIT_AESSIV          488
#define IDS_FINAL_INIT_FAILED           489
#define IDS_UNABLE_CREATE_THREAD        490
#define IDS_UNABLE_ADD_MPOINT           491
#define IDS_MOUNT_FAILED                492
#define IDS_MOUNT_TIMED_OUT             493
#define IDS_MOUNT_ERROR_WAITING         494
#define IDS_UNABLE_FIND_MPOINT          495
#define IDS_WAIT_UNMOUNT_ERROR          496
#define IDS_MPOINT_NOT_FOUND            497
#define IDS_MPOINT_NULL                 498
#define IDS_UNABLE_GET_VOLUME_INFO      499
#define IDS_UNABLE_WRITE_NEW_VOL_NAME   500
#define IDS_CANNOT_CREATE_LOCALE        501
#define IDS_NOT_FOUND_MPOINT_BASE_DIR   502
#define IDS_FAILED_CONVERT_PATH         503
#define IDS_FAILED_UNENCRYPT_PATH       504
#define IDS_FAILED_ENCRYPT_PATH         505
#define IDS_PATH_NULL                   528
#define IDS_PATH_TOO_LONG               529
#define IDS_FAILED_CANONICALIZE_PATH    530
#define IDS_INVALID_DRIVE_LETTER        531
#define IDS_PATH_TOO_SHORT              532
#define IDS_INVALID_PATH                533
#define IDS_DRIVE_NOT_MOUNTED           534
#define IDS_ERROR_LISTING_FILES         535
#define IDS_PATH_NOT_EXIST              536
#define IDS_UNABLE_GET_DOKANY_VERSION   544
#define IDS_DOKANY_VER_NOT_COMPATIBLE   545
#define IDS_DOKANY_VER_NOT_TESTED       546
#define IDS_UNABLE_INIT_LOGGING         560
#define IDS_LOGGING_TO_LOGNAME          561
#define IDS_UNABLE_OPEN_LOGNAME         562
#define IDS_RUN_WINDOW_NOT_FOUND        576
#define IDS_PROBLEM_DOKANY_VERSION      577
#define IDS_NOT_CONF_DIR_EMPTY          608
#define IDS_FAILED_OPEN_CONF            609
#define IDS_NOT_FOUND_END_CONF          610
#define IDS_CONF_TOO_BIG                611
#define IDS_CONF_EMPTY                  612
#define IDS_NOT_FOUND_BEGINNING_CONF    613
#define IDS_CANNOT_ALLOCATE_BUFFER_CONF 614
#define IDS_RAED_ERR_CONF               615
#define IDS_CONF_NOT_VALID_JSON         616
#define IDS_KEY_MISSING_IN_CONF         617
#define IDS_FAILED_BASE64_DECODE_KEY    618
#define IDS_SCRYPTOBJECT_MISSING_IN_CONF 619
#define IDS_FAILED_BASE64_DECODE_SALT   620
#define IDS_INVALID_SCRYPTOBJECT        621
#define IDS_INVALID_KEYLEN              622
#define IDS_FAILED_LOCK_BUFFER_READ_CONF 623
#define IDS_INVALID_VERSION_IN_CONF     624
#define IDS_INVALID_FSFEATUREDISABLEMASK 625
#define IDS_UNKNOWN_FEATURE_FLAG        626
#define IDS_UNABLE_CONVERT_UNKNOWN_FLAG 627
#define IDS_INVALID_LONGNAMEMAX         628
#define IDS_NO_VALUE_LONGNAMEMAX        629
#define IDS_ONLY_VERSION_2_SUPPORT      630
#define IDS_EMENAMES_REQUIRED           631
#define IDS_GCMIV128_NOT_SPECIFIED      632
#define IDS_REVERSE_MODE_WITHOUT_AESSIV 633
#define IDS_PWKEY_NOT_LOCKED            634
#define IDS_MASTER_KEY_ALREADY_SET      635
#define IDS_CANNOT_LOCK_KEY_BUFFER      636
#define IDS_FAILED_GET_RANDOM           637
#define IDS_UTF8PASS_NOT_LOCKED         638
#define IDS_CANNOT_CONVERT_PASS_UTF8    639
#define IDS_KEY_DERIVATION_FAILED       640
#define IDS_UNABLE_HKDF_ON_PWKEY        641
#define IDS_UNABLE_GENERATE_IV          642
#define IDS_UNABLE_INIT_GCM             643
#define IDS_UNABLE_GET_GCM              644
#define IDS_UNABLE_ENCRYPT_MASTER_KEY   645
#define IDS_UNABLE_BASE64_ENCODE_KEY    646
#define IDS_UNABLE_BASE64_ENCODE_SALT   647
#define IDS_ONLY_AES256SIV_WITH_REVERSE 648
#define IDS_CONF_PATH_ALREADY_EXIST     649
#define IDS_CONF_PATH_HIDDEN_EXIST      650
#define IDS_DIR_NOT_EMPTY               651
#define IDS_UNABLE_GENERATE_MASTER_KEY  652
#define IDS_CANNOT_ENCRYPT_VOLUME_NAME  653
#define IDS_CANNOT_CREATE_CONF          654
#define IDS_UNABLE_OPEN_WRITE_CONF      655
#define IDS_CANNOT_CREATE_DIRIV         656
#define IDS_MEMORY_ALLOCATION_FAILURE   657
#define IDS_APLLY_LANGUAGE_RESTART      688
#define IDS_LANGUAGE_NAME               704
#define IDR_LICENSE_CPPCRYPTFS          800
#define IDR_LICENSE_OPENSSL             801
#define IDR_LICENSE_RAPIDJSON           802
#define IDR_LICENSE_DOKANY_MIR          803
#define IDR_LICENSE_DOKANY_LIB          804
#define IDR_LICENSE_SECURY_EDIT         805
#define IDR_LICENSE_GETOPT              806
#define IDR_LICENSE_AESSIV              807
#define AFX_IDC_FONTPROP                1000
#define AFX_IDC_FONTNAMES               1001
#define IDC_DRIVE_LETTERS               1002
#define AFX_IDC_FONTSTYLES              1002
#define IDC_PATH                        1003
#define AFX_IDC_FONTSIZES               1003
#define IDC_CONFIG_PATH                 1004
#define AFX_IDC_STRIKEOUT               1004
#define AFX_IDC_UNDERLINE               1005
#define IDC_MOUNT                       1006
#define AFX_IDC_SAMPLEBOX               1006
#define IDC_PASSWORD                    1007
#define IDC_PASSWORD2                   1008
#define IDC_DISMOUNT                    1009
#define IDC_DISMOUNT_ALL                1010
#define IDC_DISMOUNT_ALL2               1011
#define IDC_EXIT                        1011
#define IDC_SELECT                      1012
#define IDC_SELECT_CONFIG_PATH          1013
#define IDC_SELECT2                     1013
#define IDC_CREATE                      1015
#define IDC_FILENAME_ENCRYPTION         1017
#define IDC_LONG_FILE_NAMES             1018
#define IDC_DATA_ENCRYPTION             1019
#define IDC_EDIT1                       1020
#define IDC_VOLUME_NAME                 1020
#define IDC_INFO                        1020
#define IDC_CACHE_KEYS_IN_MEM           1020
#define IDC_LONG_FILE_NAMES2            1021
#define IDC_REVERSE                     1021
#define IDC_CACHE_KEYS_IN_MEM2          1021
#define IDC_DENY_SERVICES_TXT           1021
#define IDC_FLUSH_AFTER_WRITE_TXT       1022
#define IDC_FILENAME_ENCRYPTION2        1022
#define IDC_LONGNAMEMAX                 1022
#define IDC_FLUSH_AFTER_WRITE_TXT2      1023
#define IDC_FLONG_NAME_MAX              1023
#define IDC_DETERMINISTIC_FILENAMES     1023
#define IDC_DETERMINISTIC_NAMES         1023
#define IDC_LIST2                       1024
#define IDC_COMPONENTS_LIST             1024
#define IDC_PROD_VERSION                1025
#define IDC_COPYRIGHT                   1026
#define IDC_CHECK1                      1027
#define IDC_READONLY                    1027
#define IDC_CASEINSENSITIVE             1027
#define IDC_AES_NI                      1027
#define IDC_LINKAGES                    1027
#define IDC_DISABLE_STREAMS             1027
#define IDC_MOUNTMANAGER                1028
#define IDC_READONLY2                   1028
#define IDC_SAVE_PASSWORD               1028
#define IDC_ENABLE_SAVING_PASSWORDS     1029
#define IDC_ENABLE_SAVING_PASSWORDS2    1030
#define IDC_NEVER_SAVE_HISTORY          1030
#define IDC_SETTINGS                    1031
#define IDC_THREADS                     1031
#define IDC_CASEINSENSITIVE2            1031
#define IDC_MULTITHREADED               1031
#define IDC_BUFFERBLOCKS                1032
#define IDC_BUFFERSIZE                  1032
#define IDC_CACHETTL                    1033
#define IDC_DEFAULTS                    1034
#define IDC_BUTTON2                     1035
#define IDC_RECOMMENDED                 1035
#define IDC_DONTSHOWAGAIN               1036
#define IDC_DELETE_SPURRIOUS_FILES      1036
#define IDC_OPEN_ON_MOUNTING            1037
#define IDC_BUTTON1                     1038
#define IDC_RESETWARNINGS               1038
#define IDC_MOUNT_POINT                 1039
#define IDC_ENCRYPT_KEYS_IN_MEMORY      1039
#define IDC_READ_ONLY                   1040
#define IDC_CACHE_KEYS_IN_MEMORY2       1040
#define IDC_CACHE_KEYS_IN_MEMORY        1040
#define IDC_FILE_NAME_ENCRYPTION        1041
#define IDC_CACHE_KEYS_IN_MEMORY3       1041
#define IDC_FAST_MOUNTING               1041
#define IDC_CASE_INSENSITIVE            1042
#define IDC_FAST_MOUNTING2              1042
#define IDC_WARN_IF_IN_USE_ON_DISMOUNTING 1042
#define IDC_WARN_IF_IN_USE_ON_DISMOUNT  1042
#define IDC_IO_BUFFER_SIZE              1043
#define IDC_MOUNT_MANAGER               1043
#define IDC_WARN_IF_IN_USE_ON_DISMOUNTING2 1043
#define IDC_DENY_OTHER_USERS            1043
#define IDC_DENY_OTHER_SESSIONS         1043
#define IDC_RECYCLE_BIN                 1044
#define IDC_IO_BUFFER_SIZE3             1044
#define IDC_IO_BUF_SIZE                 1044
#define IDC_DENY_SERVICES               1044
#define IDC_HKDF                        1045
#define IDC_ENC_KEYS_IN_MEM             1045
#define IDC_ENCRYPT_KEYS_IN_MEM         1045
#define IDC_CACHE_TTL                   1046
#define IDC_DIRIV_CACHE_HR              1047
#define IDC_CASE_CACHE_HR               1048
#define IDC_LFN_CACHE_HR                1049
#define IDC_MODE                        1050
#define IDC_KEYS_UNECRYPTED_TIME        1051
#define IDC_DEBUGINFO                   1051
#define IDC_ENCRYPT_KEYS_IN_MEM2        1051
#define IDC_DENY_OTHER_USERS_TXT        1051
#define IDC_DENY_OTHER_SESSIONS_TXT     1051
#define IDC_KEYS_UNECRYPTED_TIME2       1052
#define IDC_MOUNTED_TIME                1052
#define IDC_CHECK2                      1052
#define IDC_AUTO_MOUNT                  1052
#define IDC_FLUSH_AFTER_WRITE_EXFAT     1052
#define IDC_FLUSH_AFTER_WRITE_FAT32     1053
#define IDC_FLUSH_AFTER_WRITE_NTFS      1054
#define IDC_FLUSH_AFTER_WRITE_NOT_NTFS  1055
#define IDC_LONG_NAME_MAX               1055
#define IDC_FLUSH_AFTER_WRITE_NO_SPARSE_FILES 1056
#define IDC_SCRYPTN                     1056
#define IDC_SCRYPTMEMREQ                1057
#define IDC_APPLY                       1058
#define IDC_LANGUAGE                    1059
#define AFX_IDC_COLOR_BLACK             1100
#define AFX_IDC_COLOR_WHITE             1101
#define AFX_IDC_COLOR_RED               1102
#define AFX_IDC_COLOR_GREEN             1103
#define AFX_IDC_COLOR_BLUE              1104
#define AFX_IDC_COLOR_YELLOW            1105
#define AFX_IDC_COLOR_MAGENTA           1106
#define AFX_IDC_COLOR_CYAN              1107
#define AFX_IDC_COLOR_GRAY              1108
#define AFX_IDC_COLOR_LIGHTGRAY         1109
#define AFX_IDC_COLOR_DARKRED           1110
#define AFX_IDC_COLOR_DARKGREEN         1111
#define AFX_IDC_COLOR_DARKBLUE          1112
#define AFX_IDC_COLOR_LIGHTBROWN        1113
#define AFX_IDC_COLOR_DARKMAGENTA       1114
#define AFX_IDC_COLOR_DARKCYAN          1115
#define AFX_IDC_COLORPROP               1116
#define AFX_IDC_SYSTEMCOLORS            1117
#define AFX_IDC_PROPNAME                1201
#define AFX_IDC_PICTURE                 1202
#define AFX_IDC_BROWSE                  1203
#define AFX_IDC_CLEAR                   1204
#define AFX_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define AFX_IDD_NEWTYPEDLG              30721
#define AFX_IDD_PRINTDLG                30722
#define AFX_IDD_PREVIEW_TOOLBAR         30723
#define AFX_IDD_INSERTOBJECT            30724
#define AFX_IDD_CHANGEICON              30725
#define AFX_IDD_CONVERT                 30726
#define AFX_IDD_PASTESPECIAL            30727
#define AFX_IDD_EDITLINKS               30728
#define AFX_IDD_FILEBROWSE              30729
#define AFX_IDD_BUSY                    30730
#define AFX_IDD_OBJECTPROPERTIES        30732
#define AFX_IDD_CHANGESOURCE            30733
#define AFX_IDD_EMPTYDIALOG             30734
#define AFX_IDC_CONTEXTHELP             30977
#define AFX_IDC_MAGNIFY                 30978
#define AFX_IDC_SMALLARROWS             30979
#define AFX_IDC_HSPLITBAR               30980
#define AFX_IDC_VSPLITBAR               30981
#define AFX_IDC_NODROPCRSR              30982
#define AFX_IDC_TRACKNWSE               30983
#define AFX_IDC_TRACKNESW               30984
#define AFX_IDC_TRACKNS                 30985
#define AFX_IDC_TRACKWE                 30986
#define AFX_IDC_TRACK4WAY               30987
#define AFX_IDC_MOVE4WAY                30988
#define AFX_IDB_MINIFRAME_MENU          30994
#define AFX_IDB_CHECKLISTBOX_95         30996
#define AFX_IDR_PREVIEW_ACCEL           30997
#define AFX_IDC_MOUSE_PAN_NW            30998
#define AFX_IDC_MOUSE_PAN_N             30999
#define AFX_IDC_MOUSE_PAN_NE            31000
#define AFX_IDC_MOUSE_PAN_W             31001
#define AFX_IDC_MOUSE_PAN_HV            31002
#define AFX_IDC_MOUSE_PAN_E             31003
#define AFX_IDC_MOUSE_PAN_SW            31004
#define AFX_IDC_MOUSE_PAN_S             31005
#define AFX_IDC_MOUSE_PAN_SE            31006
#define AFX_IDC_MOUSE_PAN_HORZ          31007
#define AFX_IDC_MOUSE_PAN_VERT          31008
#define AFX_IDC_MOUSE_ORG_HORZ          31009
#define AFX_IDC_MOUSE_ORG_VERT          31010
#define AFX_IDC_MOUSE_ORG_HV            31011
#define AFX_IDC_MOUSE_MASK              31012
#define AFX_IDI_STD_MDIFRAME            31233
#define AFX_IDI_STD_FRAME               31234
#define AFX_IDD_PROPPAGE_COLOR          32257
#define AFX_IDD_PROPPAGE_FONT           32258
#define AFX_IDD_PROPPAGE_PICTURE        32259
#define ID_IDR_SHOWCPPCRYPTFS           32771
#define ID_IDR_EXITCPPCRYPTFS           32772
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define AFX_IDS_HELPMODEMESSAGE         0xE002
#define AFX_IDS_APP_TITLE_EMBEDDING     0xE003
#define AFX_IDS_COMPANY_NAME            0xE004
#define AFX_IDS_OBJ_TITLE_INPLACE       0xE005
#define AFX_IDS_APP_ID                  0xE006
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_NEW_FRAME               0xE10D
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_FORMAT_FONT                  0xE160
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_OLE_VERB_POPUP               0xE220
#define AFX_ID_PREVIEW_CLOSE            0xE300
#define AFX_ID_PREVIEW_NUMPAGE          0xE301
#define AFX_ID_PREVIEW_NEXT             0xE302
#define AFX_ID_PREVIEW_PREV             0xE303
#define AFX_ID_PREVIEW_PRINT            0xE304
#define AFX_ID_PREVIEW_ZOOMIN           0xE305
#define AFX_ID_PREVIEW_ZOOMOUT          0xE306
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_INDICATOR_KANA               0xE706
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REBAR                   0xE804
#define ID_VIEW_AUTOARRANGE             0xE805
#define ID_VIEW_SMALLICON               0xE810
#define ID_VIEW_LARGEICON               0xE811
#define ID_VIEW_LIST                    0xE812
#define ID_VIEW_DETAILS                 0xE813
#define ID_VIEW_LINEUP                  0xE814
#define ID_VIEW_BYNAME                  0xE815
#define ID_RECORD_FIRST                 0xE900
#define ID_RECORD_LAST                  0xE901
#define ID_RECORD_NEXT                  0xE902
#define ID_RECORD_PREV                  0xE903
#define AFX_TIMER_ID_FIRST              0xEC00
#define AFX_TIMER_ID_DISPLAY_AHWND_EVENT 0xEC00
#define AFX_TIMER_ID_AUTO_HIDE_SLIDE_IN_EVENT 0xEC01
#define AFX_TIMER_ID_AUTO_HIDE_SLIDE_OUT_EVENT 0xEC02
#define AFX_TIMER_ID_CHECK_AUTO_HIDE_CONDITION 0xEC03
#define AFX_TIMER_ID_DOCK_EVENT         0xEC04
#define AFX_TIMER_ID_CHECK_ROLL_STATE   0xEC05
#define AFX_TIMER_ID_VISIBILITY_TIMER   0xEC06
#define AFX_TIMER_ID_ACCELERATOR_NOTIFY_EVENT 0xEC07
#define AFX_TIMER_ID_TIMER_TRACKING     0xEC08
#define AFX_TIMER_ID_TIMER_WAIT         0xEC09
#define AFX_TIMER_ID_TIMER_CHECK        0xEC0A
#define AFX_TIMER_ID_TASK_ANIMATION     0xEC0B
#define AFX_TIMER_ID_TASK_SCROLL        0xEC0C
#define AFX_TIMER_ID_AUTOCOMMAND        0xEC0D
#define AFX_TIMER_ID_ALERT_CLOSE_POPUP  0xEC0E
#define AFX_TIMER_ID_ALERT_ANIMATION    0xEC0F
#define AFX_TIMER_ID_ALERT_CHECK_ACTIVITY 0xEC10
#define AFX_TIMER_ID_TB_SHOW_DROPDOWN   0xEC11
#define AFX_TIMER_ID_MENU_SHOW_ALL_ITEMS 0xEC12
#define AFX_TIMER_ID_OUTLOOK_BAR_SCRL_UP 0xEC13
#define AFX_TIMER_ID_OUTLOOK_BAR_SCRL_DN 0xEC14
#define AFX_TIMER_ID_MENU_POPUP_ANIMATION 0xEC15
#define AFX_TIMER_ID_MENU_POPUP_SCROLL  0xEC16
#define AFX_TIMER_ID_MENUBAR_POPUP      0xEC17
#define AFX_TIMER_ID_MENUBAR_REMOVE     0xEC18
#define AFX_TIMER_ID_RIBBONBAR_AUTO_COMMAND 0xEC19
#define AFX_TIMER_ID_RIBBONBAR_SHOW_KEYTIPS 0xEC1A
#define AFX_TIMER_ID_RIBBONPANEL_POPUP  0xEC1B
#define AFX_TIMER_ID_RIBBONPANEL_REMOVE 0xEC1C
#define AFX_TIMER_ID_RIBBONPANEL_AUTO_COMMAND 0xEC1D
#define AFX_TIMER_ID_LAST               0xEC1F
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_DESKACCESSORY           0xEFDA
#define AFX_IDS_OPENFILE                0xF000
#define AFX_IDS_SAVEFILE                0xF001
#define AFX_IDS_ALLFILTER               0xF002
#define AFX_IDS_UNTITLED                0xF003
#define AFX_IDS_SAVEFILECOPY            0xF004
#define AFX_IDS_PREVIEW_CLOSE           0xF005
#define AFX_IDS_UNNAMED_FILE            0xF006
#define AFX_IDS_HIDE                    0xF011
#define AFX_IDP_NO_ERROR_AVAILABLE      0xF020
#define AFX_IDS_NOT_SUPPORTED_EXCEPTION 0xF021
#define AFX_IDS_RESOURCE_EXCEPTION      0xF022
#define AFX_IDS_MEMORY_EXCEPTION        0xF023
#define AFX_IDS_USER_EXCEPTION          0xF024
#define AFX_IDS_INVALID_ARG_EXCEPTION   0xF025
#define AFX_IDS_PRINTONPORT             0xF040
#define AFX_IDS_ONEPAGE                 0xF041
#define AFX_IDS_TWOPAGE                 0xF042
#define AFX_IDS_PRINTPAGENUM            0xF043
#define AFX_IDS_PREVIEWPAGEDESC         0xF044
#define AFX_IDS_PRINTDEFAULTEXT         0xF045
#define AFX_IDS_PRINTDEFAULT            0xF046
#define AFX_IDS_PRINTFILTER             0xF047
#define AFX_IDS_PRINTCAPTION            0xF048
#define AFX_IDS_PRINTTOFILE             0xF049
#define AFX_IDS_OBJECT_MENUITEM         0xF080
#define AFX_IDS_EDIT_VERB               0xF081
#define AFX_IDS_ACTIVATE_VERB           0xF082
#define AFX_IDS_CHANGE_LINK             0xF083
#define AFX_IDS_AUTO                    0xF084
#define AFX_IDS_MANUAL                  0xF085
#define AFX_IDS_FROZEN                  0xF086
#define AFX_IDS_ALL_FILES               0xF087
#define AFX_IDS_SAVE_MENU               0xF088
#define AFX_IDS_UPDATE_MENU             0xF089
#define AFX_IDS_SAVE_AS_MENU            0xF08A
#define AFX_IDS_SAVE_COPY_AS_MENU       0xF08B
#define AFX_IDS_EXIT_MENU               0xF08C
#define AFX_IDS_UPDATING_ITEMS          0xF08D
#define AFX_IDS_METAFILE_FORMAT         0xF08E
#define AFX_IDS_DIB_FORMAT              0xF08F
#define AFX_IDS_BITMAP_FORMAT           0xF090
#define AFX_IDS_LINKSOURCE_FORMAT       0xF091
#define AFX_IDS_EMBED_FORMAT            0xF092
#define AFX_IDS_PASTELINKEDTYPE         0xF094
#define AFX_IDS_UNKNOWNTYPE             0xF095
#define AFX_IDS_RTF_FORMAT              0xF096
#define AFX_IDS_TEXT_FORMAT             0xF097
#define AFX_IDS_INVALID_CURRENCY        0xF098
#define AFX_IDS_INVALID_DATETIME        0xF099
#define AFX_IDS_INVALID_DATETIMESPAN    0xF09A
#define AFX_IDP_INVALID_FILENAME        0xF100
#define AFX_IDP_FAILED_TO_OPEN_DOC      0xF101
#define AFX_IDP_FAILED_TO_SAVE_DOC      0xF102
#define AFX_IDP_ASK_TO_SAVE             0xF103
#define AFX_IDP_FAILED_TO_CREATE_DOC    0xF104
#define AFX_IDP_FILE_TOO_LARGE          0xF105
#define AFX_IDP_FAILED_TO_START_PRINT   0xF106
#define AFX_IDP_FAILED_TO_LAUNCH_HELP   0xF107
#define AFX_IDP_INTERNAL_FAILURE        0xF108
#define AFX_IDP_COMMAND_FAILURE         0xF109
#define AFX_IDP_FAILED_MEMORY_ALLOC     0xF10A
#define AFX_IDP_UNREG_DONE              0xF10B
#define AFX_IDP_UNREG_FAILURE           0xF10C
#define AFX_IDP_DLL_LOAD_FAILED         0xF10D
#define AFX_IDP_DLL_BAD_VERSION         0xF10E
#define AFX_IDP_PARSE_INT               0xF110
#define AFX_IDP_PARSE_REAL              0xF111
#define AFX_IDP_PARSE_INT_RANGE         0xF112
#define AFX_IDP_PARSE_REAL_RANGE        0xF113
#define AFX_IDP_PARSE_STRING_SIZE       0xF114
#define AFX_IDP_PARSE_RADIO_BUTTON      0xF115
#define AFX_IDP_PARSE_BYTE              0xF116
#define AFX_IDP_PARSE_UINT              0xF117
#define AFX_IDP_PARSE_DATETIME          0xF118
#define AFX_IDP_PARSE_CURRENCY          0xF119
#define AFX_IDP_PARSE_GUID              0xF11A
#define AFX_IDP_PARSE_TIME              0xF11B
#define AFX_IDP_PARSE_DATE              0xF11C
#define AFX_IDP_FAILED_INVALID_FORMAT   0xF120
#define AFX_IDP_FAILED_INVALID_PATH     0xF121
#define AFX_IDP_FAILED_DISK_FULL        0xF122
#define AFX_IDP_FAILED_ACCESS_READ      0xF123
#define AFX_IDP_FAILED_ACCESS_WRITE     0xF124
#define AFX_IDP_FAILED_IO_ERROR_READ    0xF125
#define AFX_IDP_FAILED_IO_ERROR_WRITE   0xF126
#define AFX_IDP_SCRIPT_ERROR            0xF130
#define AFX_IDP_SCRIPT_DISPATCH_EXCEPTION 0xF131
#define AFX_IDP_STATIC_OBJECT           0xF180
#define AFX_IDP_FAILED_TO_CONNECT       0xF181
#define AFX_IDP_SERVER_BUSY             0xF182
#define AFX_IDP_BAD_VERB                0xF183
#define AFX_IDS_NOT_DOCOBJECT           0xF184
#define AFX_IDP_FAILED_TO_NOTIFY        0xF185
#define AFX_IDP_FAILED_TO_LAUNCH        0xF186
#define AFX_IDP_ASK_TO_UPDATE           0xF187
#define AFX_IDP_FAILED_TO_UPDATE        0xF188
#define AFX_IDP_FAILED_TO_REGISTER      0xF189
#define AFX_IDP_FAILED_TO_AUTO_REGISTER 0xF18A
#define AFX_IDP_FAILED_TO_CONVERT       0xF18B
#define AFX_IDP_GET_NOT_SUPPORTED       0xF18C
#define AFX_IDP_SET_NOT_SUPPORTED       0xF18D
#define AFX_IDP_ASK_TO_DISCARD          0xF18E
#define AFX_IDP_FAILED_TO_CREATE        0xF18F
#define AFX_IDP_FAILED_MAPI_LOAD        0xF190
#define AFX_IDP_INVALID_MAPI_DLL        0xF191
#define AFX_IDP_FAILED_MAPI_SEND        0xF192
#define AFX_IDP_FILE_NONE               0xF1A0
#define AFX_IDP_FILE_GENERIC            0xF1A1
#define AFX_IDP_FILE_NOT_FOUND          0xF1A2
#define AFX_IDP_FILE_BAD_PATH           0xF1A3
#define AFX_IDP_FILE_TOO_MANY_OPEN      0xF1A4
#define AFX_IDP_FILE_ACCESS_DENIED      0xF1A5
#define AFX_IDP_FILE_INVALID_FILE       0xF1A6
#define AFX_IDP_FILE_REMOVE_CURRENT     0xF1A7
#define AFX_IDP_FILE_DIR_FULL           0xF1A8
#define AFX_IDP_FILE_BAD_SEEK           0xF1A9
#define AFX_IDP_FILE_HARD_IO            0xF1AA
#define AFX_IDP_FILE_SHARING            0xF1AB
#define AFX_IDP_FILE_LOCKING            0xF1AC
#define AFX_IDP_FILE_DISKFULL           0xF1AD
#define AFX_IDP_FILE_EOF                0xF1AE
#define AFX_IDP_ARCH_NONE               0xF1B0
#define AFX_IDP_ARCH_GENERIC            0xF1B1
#define AFX_IDP_ARCH_READONLY           0xF1B2
#define AFX_IDP_ARCH_ENDOFFILE          0xF1B3
#define AFX_IDP_ARCH_WRITEONLY          0xF1B4
#define AFX_IDP_ARCH_BADINDEX           0xF1B5
#define AFX_IDP_ARCH_BADCLASS           0xF1B6
#define AFX_IDP_ARCH_BADSCHEMA          0xF1B7
#define AFX_IDS_OCC_SCALEUNITS_PIXELS   0xF1C0
#define AFX_IDS_STATUS_FONT             0xF230
#define AFX_IDS_TOOLTIP_FONT            0xF231
#define AFX_IDS_UNICODE_FONT            0xF232
#define AFX_IDS_MINI_FONT               0xF233
#define AFX_IDP_SQL_CONNECT_FAIL        0xF281
#define AFX_IDP_SQL_RECORDSET_FORWARD_ONLY 0xF282
#define AFX_IDP_SQL_EMPTY_COLUMN_LIST   0xF283
#define AFX_IDP_SQL_FIELD_SCHEMA_MISMATCH 0xF284
#define AFX_IDP_SQL_ILLEGAL_MODE        0xF285
#define AFX_IDP_SQL_MULTIPLE_ROWS_AFFECTED 0xF286
#define AFX_IDP_SQL_NO_CURRENT_RECORD   0xF287
#define AFX_IDP_SQL_NO_ROWS_AFFECTED    0xF288
#define AFX_IDP_SQL_RECORDSET_READONLY  0xF289
#define AFX_IDP_SQL_SQL_NO_TOTAL        0xF28A
#define AFX_IDP_SQL_ODBC_LOAD_FAILED    0xF28B
#define AFX_IDP_SQL_DYNASET_NOT_SUPPORTED 0xF28C
#define AFX_IDP_SQL_SNAPSHOT_NOT_SUPPORTED 0xF28D
#define AFX_IDP_SQL_API_CONFORMANCE     0xF28E
#define AFX_IDP_SQL_SQL_CONFORMANCE     0xF28F
#define AFX_IDP_SQL_NO_DATA_FOUND       0xF290
#define AFX_IDP_SQL_ROW_UPDATE_NOT_SUPPORTED 0xF291
#define AFX_IDP_SQL_ODBC_V2_REQUIRED    0xF292
#define AFX_IDP_SQL_NO_POSITIONED_UPDATES 0xF293
#define AFX_IDP_SQL_LOCK_MODE_NOT_SUPPORTED 0xF294
#define AFX_IDP_SQL_DATA_TRUNCATED      0xF295
#define AFX_IDP_SQL_ROW_FETCH           0xF296
#define AFX_IDP_SQL_INCORRECT_ODBC      0xF297
#define AFX_IDP_SQL_UPDATE_DELETE_FAILED 0xF298
#define AFX_IDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED 0xF299
#define AFX_IDP_SQL_FIELD_NOT_FOUND     0xF29A
#define AFX_IDP_SQL_BOOKMARKS_NOT_SUPPORTED 0xF29B
#define AFX_IDP_SQL_BOOKMARKS_NOT_ENABLED 0xF29C
#define AFX_IDS_DELETED                 0xF29D
#define AFX_IDP_DAO_ENGINE_INITIALIZATION 0xF2B0
#define AFX_IDP_DAO_DFX_BIND            0xF2B1
#define AFX_IDP_DAO_OBJECT_NOT_OPEN     0xF2B2
#define AFX_IDP_DAO_ROWTOOSHORT         0xF2B3
#define AFX_IDP_DAO_BADBINDINFO         0xF2B4
#define AFX_IDP_DAO_COLUMNUNAVAILABLE   0xF2B5
#define AFX_IDS_HTTP_TITLE              0xF2D1
#define AFX_IDS_HTTP_NO_TEXT            0xF2D2
#define AFX_IDS_HTTP_BAD_REQUEST        0xF2D3
#define AFX_IDS_HTTP_AUTH_REQUIRED      0xF2D4
#define AFX_IDS_HTTP_FORBIDDEN          0xF2D5
#define AFX_IDS_HTTP_NOT_FOUND          0xF2D6
#define AFX_IDS_HTTP_SERVER_ERROR       0xF2D7
#define AFX_IDS_HTTP_NOT_IMPLEMENTED    0xF2D8
#define AFX_IDS_CHECKLISTBOX_UNCHECK    0xF2E1
#define AFX_IDS_CHECKLISTBOX_CHECK      0xF2E2
#define AFX_IDS_CHECKLISTBOX_MIXED      0xF2E3
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_1 0xF2E4
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_2 0xF2E5
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_3 0xF2E6
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_4 0xF2E7
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_5 0xF2E8
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_6 0xF2E9
#define AFX_IDS_AUTOSAVE_RECOVERED      0xF2EA
#define AFX_IDS_PROPPAGE_UNKNOWN        0xFE01
#define AFX_IDS_COLOR_DESKTOP           0xFE04
#define AFX_IDS_COLOR_APPWORKSPACE      0xFE05
#define AFX_IDS_COLOR_WNDBACKGND        0xFE06
#define AFX_IDS_COLOR_WNDTEXT           0xFE07
#define AFX_IDS_COLOR_MENUBAR           0xFE08
#define AFX_IDS_COLOR_MENUTEXT          0xFE09
#define AFX_IDS_COLOR_ACTIVEBAR         0xFE0A
#define AFX_IDS_COLOR_INACTIVEBAR       0xFE0B
#define AFX_IDS_COLOR_ACTIVETEXT        0xFE0C
#define AFX_IDS_COLOR_INACTIVETEXT      0xFE0D
#define AFX_IDS_COLOR_ACTIVEBORDER      0xFE0E
#define AFX_IDS_COLOR_INACTIVEBORDER    0xFE0F
#define AFX_IDS_COLOR_WNDFRAME          0xFE10
#define AFX_IDS_COLOR_SCROLLBARS        0xFE11
#define AFX_IDS_COLOR_BTNFACE           0xFE12
#define AFX_IDS_COLOR_BTNSHADOW         0xFE13
#define AFX_IDS_COLOR_BTNTEXT           0xFE14
#define AFX_IDS_COLOR_BTNHIGHLIGHT      0xFE15
#define AFX_IDS_COLOR_DISABLEDTEXT      0xFE16
#define AFX_IDS_COLOR_HIGHLIGHT         0xFE17
#define AFX_IDS_COLOR_HIGHLIGHTTEXT     0xFE18
#define AFX_IDS_REGULAR                 0xFE19
#define AFX_IDS_BOLD                    0xFE1A
#define AFX_IDS_ITALIC                  0xFE1B
#define AFX_IDS_BOLDITALIC              0xFE1C
#define AFX_IDS_SAMPLETEXT              0xFE1D
#define AFX_IDS_DISPLAYSTRING_FONT      0xFE1E
#define AFX_IDS_DISPLAYSTRING_COLOR     0xFE1F
#define AFX_IDS_DISPLAYSTRING_PICTURE   0xFE20
#define AFX_IDS_PICTUREFILTER           0xFE21
#define AFX_IDS_PICTYPE_UNKNOWN         0xFE22
#define AFX_IDS_PICTYPE_NONE            0xFE23
#define AFX_IDS_PICTYPE_BITMAP          0xFE24
#define AFX_IDS_PICTYPE_METAFILE        0xFE25
#define AFX_IDS_PICTYPE_ICON            0xFE26
#define AFX_IDS_COLOR_PPG               0xFE28
#define AFX_IDS_COLOR_PPG_CAPTION       0xFE29
#define AFX_IDS_FONT_PPG                0xFE2A
#define AFX_IDS_FONT_PPG_CAPTION        0xFE2B
#define AFX_IDS_PICTURE_PPG             0xFE2C
#define AFX_IDS_PICTURE_PPG_CAPTION     0xFE2D
#define AFX_IDS_PICTUREBROWSETITLE      0xFE30
#define AFX_IDS_BORDERSTYLE_0           0xFE31
#define AFX_IDS_BORDERSTYLE_1           0xFE32
#define AFX_IDS_VERB_EDIT               0xFE40
#define AFX_IDS_VERB_PROPERTIES         0xFE41
#define AFX_IDP_PICTURECANTOPEN         0xFE83
#define AFX_IDP_PICTURECANTLOAD         0xFE84
#define AFX_IDP_PICTURETOOLARGE         0xFE85
#define AFX_IDP_PICTUREREADFAILED       0xFE86
#define AFX_IDP_E_ILLEGALFUNCTIONCALL   0xFEA0
#define AFX_IDP_E_OVERFLOW              0xFEA1
#define AFX_IDP_E_OUTOFMEMORY           0xFEA2
#define AFX_IDP_E_DIVISIONBYZERO        0xFEA3
#define AFX_IDP_E_OUTOFSTRINGSPACE      0xFEA4
#define AFX_IDP_E_OUTOFSTACKSPACE       0xFEA5
#define AFX_IDP_E_BADFILENAMEORNUMBER   0xFEA6
#define AFX_IDP_E_FILENOTFOUND          0xFEA7
#define AFX_IDP_E_BADFILEMODE           0xFEA8
#define AFX_IDP_E_FILEALREADYOPEN       0xFEA9
#define AFX_IDP_E_DEVICEIOERROR         0xFEAA
#define AFX_IDP_E_FILEALREADYEXISTS     0xFEAB
#define AFX_IDP_E_BADRECORDLENGTH       0xFEAC
#define AFX_IDP_E_DISKFULL              0xFEAD
#define AFX_IDP_E_BADRECORDNUMBER       0xFEAE
#define AFX_IDP_E_BADFILENAME           0xFEAF
#define AFX_IDP_E_TOOMANYFILES          0xFEB0
#define AFX_IDP_E_DEVICEUNAVAILABLE     0xFEB1
#define AFX_IDP_E_PERMISSIONDENIED      0xFEB2
#define AFX_IDP_E_DISKNOTREADY          0xFEB3
#define AFX_IDP_E_PATHFILEACCESSERROR   0xFEB4
#define AFX_IDP_E_PATHNOTFOUND          0xFEB5
#define AFX_IDP_E_INVALIDPATTERNSTRING  0xFEB6
#define AFX_IDP_E_INVALIDUSEOFNULL      0xFEB7
#define AFX_IDP_E_INVALIDFILEFORMAT     0xFEB8
#define AFX_IDP_E_INVALIDPROPERTYVALUE  0xFEB9
#define AFX_IDP_E_INVALIDPROPERTYARRAYINDEX 0xFEBA
#define AFX_IDP_E_SETNOTSUPPORTEDATRUNTIME 0xFEBB
#define AFX_IDP_E_SETNOTSUPPORTED       0xFEBC
#define AFX_IDP_E_NEEDPROPERTYARRAYINDEX 0xFEBD
#define AFX_IDP_E_SETNOTPERMITTED       0xFEBE
#define AFX_IDP_E_GETNOTSUPPORTEDATRUNTIME 0xFEBF
#define AFX_IDP_E_GETNOTSUPPORTED       0xFEC0
#define AFX_IDP_E_PROPERTYNOTFOUND      0xFEC1
#define AFX_IDP_E_INVALIDCLIPBOARDFORMAT 0xFEC2
#define AFX_IDP_E_INVALIDPICTURE        0xFEC3
#define AFX_IDP_E_PRINTERERROR          0xFEC4
#define AFX_IDP_E_CANTSAVEFILETOTEMP    0xFEC5
#define AFX_IDP_E_SEARCHTEXTNOTFOUND    0xFEC6
#define AFX_IDP_E_REPLACEMENTSTOOLONG   0xFEC7

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
