#pragma once

#define PER_FILESYSTEM_THREADS_DEFAULT 1
#define PER_FILESYSTEM_THREADS_RECOMMENEDED 0

#define BUFFERBLOCKS_DEFAULT 1
#define BUFFERBLOCKS_RECOMMENDED 16

#define CACHETTL_DEFAULT 1
#define CACHETTL_RECOMMENDED 10

#define CASEINSENSITIVE_DEFAULT 0
#define CASEINSENSITIVE_RECOMMENDED 1
